name: MyChestCmd
main: com.github.smk7758.MyChestCmd.Main
version: 0.0.4
author: smk7758
permissions:
  MyChestCmd.*:
    description: Gives the user access to all command.
    children:
      MyChestCmd.reload: true
      MyChestCmd.debug: true
      MyHomeCmd.show_all_list
      MyChestCmd.chest: true
      MyChestCmd.make: true
      MyChestCmd.delete: true
      MyChestCmd.list: true
      MyChestCmd.ender
    default: false
  MyChestCmd.reload:
    description: Gives the user access to MyChestCmd reload command.
    default: false
  MyChestCmd.debug:
    description: Gives the user access to MyChestCmd debug command.
    default: false
  MyChestCmd.show_all_list:
    description: Gives the user access to MyChestCmd show_all_list command.
    default: false
  MyChestCmd.chest:
    description: Gives the user access to Chest command.
    default: false
  MyChestCmd.make:
    description: Gives the user access to MakeChest command.
    default: false
  MyChestCmd.delete:
    description: Gives the user access to DeleteChest command.
    default: false
  MyChestCmd.list:
    description: Gives the user access to ListChest command.
    default: false
  MyChestCmd.ender:
    description: Gives the user access to MyChestCmdEnder command.
    default: false
commands:
  MyChestCmd:
    description: MyChestCmd.
    aliases: mcc
  Chest:
    description: MyChestCmd.
  MyChestCmd:
    description: MyChestCmd.
    aliases: mcc
  MakeChest:
    description: MyChestCmd.
    aliases: chestmake
  DeleteChest:
    description: MyChestCmd.
    aliases: chestdelete, delChest, Chestdel
  ListChest:
    description: MyChestCmd.
    aliases: chestlist
  MyChestCmdEnder:
    description: MyChestCmd.
    aliases: emcc, mcce